### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by renato-lombardo** [janursa/CppyABM#1]
I tried to install CppyABM on my intel i7 / Linux Ubuntu 20.10  PC using the following command:
`pip install  --upgrade cppyabm` but it failed with the following error:

`CMake Error: The source directory "/tmp/pip-install-9s7c7orp/cppyabm_e7726308f6224749b26bc304ed44fd5d" does not appear to contain CMakeLists.txt.`
I see the CMakeList.txt is actually present in the github repo, but I don't understad the source of this error.
Alternatively I tried downloading the zip file from github and using:
`python setup install --user` but it failed with this error:
`/home/renato/Scaricati/CppyABM-master/include/cppyabm/bases.h:14:9: fatal error: mach/mach.h: File o directory non esistente
   14 | #include<mach/mach.h>`
(translated from Italian: "File or directory is missing")

Do you have any suggestions on how to fix this?
Thanks.
Renato

**Comment by janursa** [comment]
Hey Renato,
Thank you for your email and the raised error.
I will check it out and come back to you.
Best
Jalil

**Comment by janursa** [comment]
can you pls try now and let me know? pls download and use 
python setup.py install --user

**Comment by renato-lombardo** [comment]
I tried again `python setup.py install --user with` commit `54e1ee5`  and got this error:

```
/home/renato/Scaricati/CppyABM-master/cppyabm/binds.cpp:32:5: error: ‘patch_obj’ was not declared in this scope
   32 |     patch_obj = bind_tools::expose_patch<expEnv,expAgent,expPatch,tramPatch>(m,"Patch");
```

**Comment by janursa** [comment]
should be fixed now. pls try and let me know. thanks

**Comment by renato-lombardo** [comment]
It seems that the installation worked, this time. I will try to use it in the next days.

Thank you!
